# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
print("Number of documents in result:", establishments.count_documents(query))

# Display the first document in the results using pprint
print("First result:")
results = establishments.find(query)
pprint(results[0])

Number of documents in result: 41
First result:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64bc252bbe62b02c7c70f36c'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
fields = {"BusinessName": 1, "scores.Hygiene": 1}
results = list(establishments.find(query, fields))
hygiene_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Number of rows in dataframe: ", len(results))

# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows in dataframe:  41

                        _id               BusinessName           scores
0  64bc252bbe62b02c7c70f36c        The Chase Rest Home  {'Hygiene': 20}
1  64bc252bbe62b02c7c70f6ea                 Brenalwood  {'Hygiene': 20}
2  64bc252bbe62b02c7c70f9f7              Melrose Hotel  {'Hygiene': 20}
3  64bc252bbe62b02c7c70fbe4              Seaford Pizza  {'Hygiene': 20}
4  64bc252bbe62b02c7c70fbf2              Golden Palace  {'Hygiene': 20}
5  64bc252cbe62b02c7c710592           Ashby's Butchers  {'Hygiene': 20}
6  64bc252cbe62b02c7c7107b4  South Sea Express Cuisine  {'Hygiene': 20}
7  64bc252cbe62b02c7c711cde              Golden Palace  {'Hygiene': 20}
8  64bc252cbe62b02c7c712123             The Tulip Tree  {'Hygiene': 20}
9  64bc252cbe62b02c7c712931                      F & S  {'Hygiene': 20}

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"LocalAuthorityName": {"$regex": "London"}, "RatingValue": {"$gte": 4}}

# Use count_documents to display the number of documents in the result
print("Number of documents in result:", establishments.count_documents(query))

# # Display the first document in the results using pprint
print("First result:")
results = establishments.find(query)
pprint(results[0])

Number of documents in result: 33
First result:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64bc252cbe62b02c7c710d87'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [9]:
# Convert the result to a Pandas DataFrame
fields = {"BusinessName": 1, "LocalAuthorityName": 1, "RatingValue": 1}
results = list(establishments.find(query, fields))
rating_value_greater_than_four = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Number of rows in dataframe: ", len(results))

# Display the first 10 rows of the DataFrame
rating_value_greater_than_four.head(10)

Number of rows in dataframe:  33

,_id,BusinessName,RatingValue,LocalAuthorityName
0,64bc252cbe62b02c7c710d87,Charlie's,4,City of London Corporation
1,64bc252cbe62b02c7c7110ac,Mv City Cruises Erasmus,5,City of London Corporation
2,64bc252cbe62b02c7c711bf6,Benfleet Motor Yacht Club,4,City of London Corporation
3,64bc252cbe62b02c7c7129f9,Tilbury Seafarers Centre,5,City of London Corporation
4,64bc252cbe62b02c7c7129fc,Coombs Catering t/a The Lock and Key,5,City of London Corporation
5,64bc252cbe62b02c7c713102,Mv Valulla,5,City of London Corporation
6,64bc252dbe62b02c7c71520e,Tereza Joanne,5,City of London Corporation
7,64bc252dbe62b02c7c7155d5,Brick Lane Brews,4,City of London Corporation
8,64bc252dbe62b02c7c7155ec,The Nuance Group (UK) Limited,5,City of London Corporation
9,64bc252dbe62b02c7c7155f0,City Bar & Grill,5,City of London Corporation

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [10]:
# Search within 0.01 degree on either side of the latitude and longitude.
degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000
latitude_max = latitude + degree_search
latitude_min = latitude - degree_search
longitude_max = longitude + degree_search
longitude_min = longitude - degree_search

# Rating value must equal 5
query = {"RatingValue": 5, 
         "geocode.latitude": {"$lte": latitude_max, "$gte": latitude_min},
         "geocode.longitude": {"$lte": longitude_max, "$gte": longitude_min}}

# Sort by hygiene score
sort =  [("scores.Hygiene", -1)]

# Limit to top 5 results
limit = 5

# Print the results
nearest_list = list(establishments.find(query).sort(sort).limit(limit))
pprint(nearest_list)

[{'AddressLine1': '101 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Lucky Food & Wine',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.024793263386,
  'FHRSID': 695287,
  'LocalAuthorityBusinessID': 'PI/000182135',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SB',
  'RatingDate': '2022-06-25T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64bc252cbe62b02c7c714c6a'),
  'geocode': {'latitude': 51.4878934, 'longitude': 0.0910104},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695287',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '104 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Everest Stores Ltd',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.041728368117,
  'FHRSID': 695033,
  'LocalAuthorityBusinessID': 'PI/000172986',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SJ',
  'RatingDate': '2021-09-13T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64bc252cbe62b02c7c714c90'),
  'geocode': {'latitude': 51.4876718, 'longitude': 0.0903232},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695033',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '102 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Premier Express',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.038806595731,
  'FHRSID': 695566,
  'LocalAuthorityBusinessID': 'PI/000188497',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SJ',
  'RatingDate': '2021-06-10T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64bc252cbe62b02c7c714c88'),
  'geocode': {'latitude': 51.4877234, 'longitude': 0.0904552},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695566',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 5, 'Structural': 0}},
 {'AddressLine1': '112 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'Fineway Cash & Carry',
  'BusinessType': 'Retailers - other',
  'BusinessTypeID': 4613,
  'ChangesByServerID': 0,
  'Distance': 4647.016995291011,
  'FHRSID': 694606,
  'LocalAuthorityBusinessID': 'PI/000116584',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1SJ',
  'RatingDate': '2020-10-20T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64bc252cbe62b02c7c714c5d'),
  'geocode': {'latitude': 51.4876089, 'longitude': 0.0909382},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694606',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '152 Plumstead High Street',
  'AddressLine2': '',
  'AddressLine3': 'Plumstead',
  'AddressLine4': 'Greenwich',
  'BusinessName': 'TIWA N TIWA African Restaurant Ltd',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4646.930146257832,
  'FHRSID': 1069652,
  'LocalAuthorityBusinessID': 'PI/000206841',
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'SE18 1JQ',
  'RatingDate': '2020-10-24T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('64bc252cbe62b02c7c714b8c'),
  'geocode': {'latitude': 51.4870351, 'longitude': 0.0927429},
  'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1069652',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}]

In [11]:
# Convert result to Pandas DataFrame
nearest_df = pd.DataFrame(nearest_list)
nearest_df.head()

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,64bc252cbe62b02c7c714c6a,695287,0,PI/000182135,Lucky Food & Wine,Retailers - other,4613,101 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0910104, 'latitude': 51.4878934}",,4647.024793,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,64bc252cbe62b02c7c714c90,695033,0,PI/000172986,Everest Stores Ltd,Retailers - other,4613,104 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0903232, 'latitude': 51.4876718}",,4647.041728,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,64bc252cbe62b02c7c714c88,695566,0,PI/000188497,Premier Express,Retailers - other,4613,102 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 5, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.0904552, 'latitude': 51.4877234}",,4647.038807,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,64bc252cbe62b02c7c714c5d,694606,0,PI/000116584,Fineway Cash & Carry,Retailers - other,4613,112 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0909382, 'latitude': 51.4876089}",,4647.016995,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,64bc252cbe62b02c7c714b8c,1069652,0,PI/000206841,TIWA N TIWA African Restaurant Ltd,Restaurant/Cafe/Canteen,1,152 Plumstead High Street,,Plumstead,...,http://www.royalgreenwich.gov.uk,health@royalgreenwich.gov.uk,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0927429, 'latitude': 51.4870351}",,4646.930146,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [12]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {"$match": {"scores.Hygiene": 0}}

# 2. Groups the matches by Local Authority
group_query = {"$group": {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}}

# 3. Sorts the matches from highest to lowest
sort_values = {"$sort": {"count": -1}}

# Print the number of documents in the result
pipeline = [match_query, group_query, sort_values]
results = list(establishments.aggregate(pipeline))
print("Number of documents in result: ", len(results))

# Print the first 10 results
pprint(results[0:10])

Number of documents in result:  55
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [13]:
# Convert the result to a Pandas DataFrame
results_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(results_df))

# Display the first 10 rows of the DataFrame
results_df.head(10)

Rows in DataFrame:  55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542